
server:
  port: 9001

spring:
  application:
    name: AIOFirstUser

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aiofirst?useSSL=false&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: aio
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  profiles:
    include: dev

logging:
  level:
    org:
      springframework:
        security:
          web: trace