server:
  port: 9001

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${rds.kakaoid}
            client-secret: ${rds.kakaosecret}
            scope:
              - profile_nickname
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: ${rds.kakaoredirect}
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  application:
    name: AIOFirstUser

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  profiles:
    include: dev

cloud:
  aws:
    credentials:
      access-key: ${rds.s3accesskey}
      secret-key: ${rds.s3secretkey}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${rds.s3bucket}


kakaopay:
  secretKey: ${rds.kakaopaysecretkey}
  cid: ${rds.kakaopaycid}
  readyUrl: https://open-api.kakaopay.com/online/v1/payment/ready
  approveUrl: https://open-api.kakaopay.com/online/v1/payment/approve
  refundUrl: https://open-api.kakaopay.com/online/v1/payment/cancel

jwt:
  secret: ${rds.jwt}