server:
  port: 80

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${rds.kakaoId}
            client-secret: ${rds.kakaoSecret}
            scope:
              - profile_nickname
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: ${rds.kakaoRedirect}
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  application:
    name: AIOFirstUser

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.database}?useSSL=false&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

cloud:
  aws:
    credentials:
      access-key: ${rds.s3AccessKey}
      secret-key: ${rds.s3SecretKey}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${rds.s3bucket}


kakaopay:
  secretKey: ${rds.kakaoPaySecretKey}
  cid: ${rds.kakaoPayCid}
  readyUrl: https://open-api.kakaopay.com/online/v1/payment/ready
  approveUrl: https://open-api.kakaopay.com/online/v1/payment/approve
  refundUrl: https://open-api.kakaopay.com/online/v1/payment/cancel
  server: http://13.124.160.75

jwt:
  secret: ${rds.jwt}